# 
# LogUI Server docker-compose File
# 
# Author: David Maxwell
# Date: 2020-11-16
#

version: "3.0"

services:
  proxy:
    build:
      context: ./proxy
    restart: always
    ports:
      - ${PROXY_LISTEN_ON}:8000
    volumes:
      - static:/logui/static/
    networks:
      - frontend

  http-worker:
    build:
        context: ./
        dockerfile: ./worker/Dockerfile
        args:
          - SECRET_KEY=${SECRET_KEY}  # This is required for collectstatic to work.
    env_file: .env
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    restart: always
    volumes:
      - static:/logui/static/
    networks:
      - frontend
      - backend

  # websocket-worker:
  #   networks:
  #     - frontend
  #     - backend

  # cache:
  #   networks:
  #     - backend

  # db:
  #   networks:
  #     - backend

  # logdb:
  #   networks:
  #     - backend

volumes:
  static:
  data:

networks:
  frontend:
  backend: