# 
# LogUI Server docker-compose File
# 
# Author: David Maxwell
# Date: 2021-03-26
#

version: "3.0"

services:
  proxy:
    image: 543824727987.dkr.ecr.eu-west-1.amazonaws.com/logui-server:server-proxy-latest
    restart: always
    depends_on:
      - http-worker
      - websocket-worker
    ports:
      - ${PROXY_LISTEN_ON}:8000
    volumes:
      - static:/logui/worker/static/
    networks:
      - frontend

  http-worker:
    image: 543824727987.dkr.ecr.eu-west-1.amazonaws.com/logui-server:http-worker-latest
    env_file: .env
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - SECRET_KEY=${SECRET_KEY}  # This is required for collectstatic to work
    restart: always
    volumes:
      - static:/logui/worker/static/
    networks:
      - frontend
      - backend
  
  websocket-worker:
    image: 543824727987.dkr.ecr.eu-west-1.amazonaws.com/logui-server:websocket-worker-latest
    command: daphne -b 0.0.0.0 -p 8000 worker.asgi:logui_application
    env_file: .env
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - SECRET_KEY=${SECRET_KEY}
    restart: always
    volumes:
      - static:/logui/worker/static/
    networks:
      - frontend
      - backend
  
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=logui
      # - PGDATA=/logui/data/
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend
  
  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - mongo:/data/db
      - mongo:/data/configdb
    networks:
      - backend

volumes:
  static:
  db:
  mongo:

networks:
  frontend:
  backend:
